### ISSUE TITLE
Value is not a boolean

### ISSUE THREAD

**Issue by lucaslaurent04** [equalframework/equal#112]
https://github.com/equalframework/equal/blob/c9575b7ee360fedcd55798192f3969d0e6c6aa45/lib/equal/orm/usages/UsageNumber.class.php#L67-L75

$value is a boolean, so parsed to string:
- false -> "" (empty string)
- true -> "1"

=> false is not considered as boolean

**Comment by cedricfrancoys** [comment]
fixed in 4584444
