### ISSUE TITLE
Console thread overwritten because same time

### ISSUE THREAD

**Issue by lucaslaurent04** [equalframework/equal#115]
https://github.com/equalframework/equal/blob/a867c1947da41725b0a8014309818bb4d8e5bd3b/public/console.php#L672

If multiple threads have the same time only the last is kept.

This means that for the moment some threads do not appear on the console.

Example:

No filter used
![image](https://github.com/equalframework/equal/assets/3625888/f7e2f4d3-5fce-4460-b9c6-9a42c97a3938)

Filter on level used
![image](https://github.com/equalframework/equal/assets/3625888/a01d4c81-1a5c-4542-829b-4013554a2ca7)

the errors does not show in the first image, because other threads have the same time

**Comment by cedricfrancoys** [comment]
Fixed in 0e2ec981c439158180b40b3fd6a8880802109040
