### ISSUE TITLE
Cannot return null if method return type is non-nullable

### ISSUE THREAD

**Issue by lucaslaurent04** [equalframework/equal#167]
https://github.com/equalframework/equal/blob/ab6ca5adbce47fdb3614c4c52a630ba0dbe5b6d8/lib/equal/orm/Model.class.php#L361-L375

Cannot return null if method return type is non-nullable

**Comment by cedricfrancoys** [comment]
I cannot find any  reference to this specific error message.
Is it from the IDE or a notice from PHP and, in the latter case, for which PHP version ?

**Comment by lucaslaurent04** [comment]
I think it is my IDE that does not detect the absence of declare(strict_types=1); so it sees it as an error.

Either way, isn't it a bad Idea to specify a return type that is not correct, why not use  : ?Field.
I rather have a method with no return type, than one with an incomplete/incorrect one. But that a personal preference.
