### ISSUE TITLE
Domain object.id parse bug

### ISSUE THREAD

**Issue by lucaslaurent04** [equalframework/equal#177]
https://github.com/equalframework/equal/blob/0c6cb3d44b8e7a2307bee941d111490f1044c65f/lib/equal/orm/Domain.class.php#L125

Should'nt the code above be:

```php
$target = substr($value, strlen('object.')); 
```

Else target will always be "object." because the $value is like "object.country_id"

**Comment by cedricfrancoys** [comment]
fixed in commit 583106
https://github.com/equalframework/equal/commit/5831068fe117712e492745c2aac106cdc32d65f8
