### ISSUE TITLE
Model onchange problem - unknown class

### ISSUE THREAD

**Issue by lucaslaurent04** [equalframework/equal#88]
When the Model onchange occurs, there is a check on whether the value is a sub class of 'equal\orm\Model' or not.  (is_subclass_of)

https://github.com/equalframework/equal/blob/74e54b7c03e7f75450d2b451d1e78d9ce18156bd/packages/core/actions/model/onchange.php#L148

In certain cases it throws an exception

https://github.com/equalframework/equal/blob/74e54b7c03e7f75450d2b451d1e78d9ce18156bd/lib/equal/orm/ObjectManager.class.php#L1192

Example of values that throw: "22", "test"
Example of values that do not throw: "test with spaces", "url://test"

I think that when is_subclass_of does autoload the 22.php or test.php it throw the error. -> so onchange does not work.
But when the string value does not seem like a class/file at all, is_subclass_of does not try to autoload. -> so onchange works.

**Comment by cedricfrancoys** [comment]
Code has been changed this way to prevent calling `is_subclass_of` on non-objects:

```
if(is_object($value)) {
            if(is_subclass_of($value, 'equal\orm\Model')) {
                $result[$field] = $value->toArray();
            }
            else {
                $result[$field] = serialize($value);
            }
        }
        else {
            $f = $model->getField($field);
            // adapt received values based on their type (as defined in schema)
            $result[$field] = $adapter->adaptOut($value, $f->getUsage());
        }
```
