### ISSUE TITLE
Get all controllers if no package is given, in core/data/config/controllers.php

### ISSUE THREAD

**Issue by tomvvd** [equalframework/equal#97]
For the feature 'Pipeline' of workbench, I need a data provider that returns me the list of all controllers if no package is specified.

Something like that :
https://github.com/equalframework/equal/blob/97d50e454643c7aaf8ccfab368aa1700b84017b4/packages/core/data/config/classes.php#L80C1-L92C2

**Comment by cedricfrancoys** [comment]
fixed by commit [a2918d](https://github.com/equalframework/equal/commit/a2918de689cff55790095ff20512b4a5236ef061)

**Comment by cedricfrancoys** [comment]
closed
